import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Theo Poette - Personal website</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          <span className="text-purple-300">Theo Poette</span> personal website
        </h1>
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Under construction 🚧
        </h1>
      </main>
    </>
  );
};

export default Home;
